### ISSUE TITLE
design: Todo 페이지 style 수정

### ISSUE THREAD

**Issue by khv2644511** [khv2644511/wanted-pre-onboarding-frontend#41]
# Todo 페이지 style 수정
## 작업 내용
- [x] todo 추가 버튼 레이아웃 수정
- [x] input 내 padding 추가
- [x] Todo main 높이 수정
